[package]
name = "soteria"
description = "Soteria is a toolkit for writing symbolic bug-finding tools"
license = "BSD-3-Clause"
version = "0.0.2"
edition = "2021"

[[bin]]
name = "soteria"
path = "soteria-rust/bin-rs/main.rs"
