# This is a basic workflow to help you get started with Actions

name: CI

permissions: read-all
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Z3
        uses: cda-tum/setup-z3@v1
        id: z3
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.0
          dune-cache: true
      - name: setup dependencies
        run: opam install . --deps-only --with-test --with-doc --yes
      - name: build
        run: opam exec -- dune build @all
      - name: test
        run: opam exec -- dune test
