# This is a basic workflow to help you get started with Actions

name: CI

permissions: read-all
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}-deps:main
    steps:
      # Setup steps: checkout, z3, node, ocaml
      - uses: actions/checkout@v4
      - name: install dependencies
        run: opam install . --deps-only --with-test --with-doc -y
      - name: install ocamformat
        run: opam install ocamlformat.0.27.0 -y
      - name: build-all
        run: opam exec -- dune build @all
      - name: test-all
        run: opam exec -- dune runtest
      - name: format-check
        run: opam exec -- dune build @fmt
      
      
