# This is a basic workflow to help you get started with Actions

name: CI

permissions: read-all
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        operating-system: [macos-latest, macos-13]
    runs-on: ${{ matrix.operating-system }}
    steps:
      # Setup steps: checkout, z3, node, ocaml
      - uses: actions/checkout@v4
      # OCaml build and tests
      # Building js stuff
      # Packaging OCaml distribution and sending it as artifact
      - uses: docker/setup-buildx-action@v3
        with:
          version: latest
          install: true
      - run: docker build -t all-deps -f .docker/all-deps.Dockerfile .
      - run: docker build -f .docker/tests/Dockerfile .
