# This is a basic workflow to help you get started with Actions

name: CI

permissions: read-all
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        operating-system: [macos-latest, macos-13]
    runs-on: ${{ matrix.operating-system }}
    steps:
      # Setup steps: checkout, z3, node, ocaml
      - uses: actions/checkout@v4
      - name: Setup Z3
        uses: cda-tum/setup-z3@v1
        id: z3
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dune
        run: curl -fsSL https://get.dune.build/install | sh
      # OCaml build and tests
      - name: lock
        run: dune pkg lock
      - name: OCaml build
        run: dune build
      - name: OCaml test
        run: dune test
      # Building js stuff
      - name: Install JS dependencies
        run: yarn install
      - name: Build JS stuff
        run: yarn compile
      # Packaging OCaml distribution and sending it as artifact
      - name: OCaml zip file creation
        run: make package
      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.operating-system }}-package
          path: package
          if-no-files-found: error

  test-package:
    strategy:
      matrix:
        operating-system: [macos-latest, macos-13]
    runs-on: ${{ matrix.operating-system }}
    needs: build
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.operating-system }}-package
      - name: Add executable permissions
        run: |
          chmod +x ./bin/bfa-c
          chmod +x ./bin/z3
      - name: Write dummy C file
        run: echo "int main() { return 12; }" > test.c
      - run: DYLD_LIBRARY_PATH=./lib:$DYLD_LIBRARY_PATH ./bin/bfa-c exec-main test.c
        env:
          BFA_Z3_PATH: ./bin/z3
          CERB_INSTALL_PREFIX: .

